import lesson from "./lesson";
import article from "./article";
import quest from "./quest";
import category from "./category";
import roadmap from "./roadmap";
import blogPost from "./blogPost";
import event from "./event";
import question from "./question";
import questionCategory from "./questionCategory";
import feedback from "./feedback";
import feedbackCategory from "./feedbackCategory";
import knowledge from "./knowledge";
import knowledgeCategory from "./knowledgeCategory";
import userOutput from "./userOutput";
import training from "./training";
import trainingTask from "./trainingTask";
import customContainer from "./objects/customContainer";
import tableBlock from "./objects/tableBlock";
import linkCard from "./objects/linkCard";
import tableOfContents from "./objects/tableOfContents";

export const schemaTypes = [category, lesson, quest, article, roadmap, blogPost, event, question, questionCategory, feedback, feedbackCategory, knowledge, knowledgeCategory, userOutput, training, trainingTask, customContainer, tableBlock, linkCard, tableOfContents];
