import lesson from "./lesson";
import article from "./article";
import quest from "./quest";
import category from "./category";
import roadmap from "./roadmap";
import blogPost from "./blogPost";
import event from "./event";
import question from "./question";
import questionCategory from "./questionCategory";
import feedback from "./feedback";
import feedbackCategory from "./feedbackCategory";
import userOutput from "./userOutput";
import training from "./training";
import trainingTask from "./trainingTask";
import guide from "./guide";
import customContainer from "./objects/customContainer";
import tableBlock from "./objects/tableBlock";
import linkCard from "./objects/linkCard";
import tableOfContents from "./objects/tableOfContents";
import sectionHeading from "./objects/sectionHeading";
import cardGrid from "./objects/cardGrid";
import pullQuote from "./objects/pullQuote";
import stepFlow from "./objects/stepFlow";
import divider from "./objects/divider";

export const schemaTypes = [category, lesson, quest, article, roadmap, blogPost, event, question, questionCategory, feedback, feedbackCategory, userOutput, training, trainingTask, guide, customContainer, tableBlock, linkCard, tableOfContents, sectionHeading, cardGrid, pullQuote, stepFlow, divider];
