// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fryogvfhymnpiqwssmuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyeW9ndmZoeW1ucGlxd3NzbXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjgxMDc2MjEsImV4cCI6MjA0MzY4MzYyMX0.QR-060G9GY5ZMFw1potnVjF3C79KxCUNRQokmj1lHug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);