export const MOCK_CONTENTS = [
  {
    id: "1",
    title: "Figmaの基本操作マスター",
    description: "Figmaの基本的な使い方から応用テクニックまでを解説",
    type: "video",
    categories: ["figma", "ui-design"],
    thumbnailUrl: "/placeholder.svg",
    accessLevel: "free",
    videoUrl: "https://player.vimeo.com/video/76979871",
    freeVideoUrl: "https://player.vimeo.com/video/76979871",
    videoDuration: 1800,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
    published: true,
  },
  {
    id: "2",
    title: "UIデザイントレンド2025",
    description: "2025年のUIデザイントレンドと実装方法",
    type: "article",
    categories: ["ui-design"],
    thumbnailUrl: "/placeholder.svg",
    accessLevel: "standard",
    content: "2025年のUIデザイントレンドとしては、ニューモーフィズムの進化版やマイクロインタラクションの高度な活用、AI支援のパーソナライズドUIなどが注目されています。\n\nこの記事では、これらのトレンドについて詳しく解説し、実際の実装方法やユーザーエクスペリエンスへの影響について考察します。",
    freeContent: "2025年のUIデザイントレンドとしては、ニューモーフィズムの進化版やマイクロインタラクションの高度な活用などが注目されています。",
    createdAt: "2025-02-20T14:30:00Z",
    updatedAt: "2025-02-25T09:15:00Z",
    published: true,
  },
  {
    id: "3",
    title: "UXリサーチの手法と実践",
    description: "効果的なUXリサーチの方法とその活用法",
    type: "tutorial",
    categories: ["ux-design", "learning"],
    thumbnailUrl: "/placeholder.svg",
    accessLevel: "standard",
    content: "UXリサーチは製品開発において非常に重要なプロセスです。ユーザーインタビュー、ユーザビリティテスト、A/Bテスト、アイトラッキングなど様々な手法があります。\n\nこのチュートリアルでは、これらの手法を実際のプロジェクトでどのように活用すればよいか、また得られたデータをどのように分析し、デザインに反映させるかについて解説します。",
    freeContent: "UXリサーチは製品開発において非常に重要なプロセスです。ユーザーインタビュー、ユーザビリティテスト、A/Bテストなど様々な手法があります。",
    createdAt: "2025-03-05T11:45:00Z",
    updatedAt: "2025-03-10T16:20:00Z",
    published: true,
  },
  {
    id: "4",
    title: "デザインシステムの構築と運用",
    description: "効率的なデザインシステムの作り方と組織での活用方法",
    type: "course",
    categories: ["ui-design", "ux-design", "learning"],
    thumbnailUrl: "/placeholder.svg",
    accessLevel: "growth",
    lessonIds: ["4-1", "4-2", "4-3", "4-4"],
    createdAt: "2025-01-30T08:20:00Z",
    updatedAt: "2025-04-01T13:10:00Z",
    published: true,
  },
  {
    id: "5",
    title: "コミュニティ限定ワークショップ",
    description: "メンバー限定のインタラクティブワークショップ",
    type: "video",
    categories: ["member", "learning"],
    thumbnailUrl: "/placeholder.svg",
    accessLevel: "community",
    videoUrl: "https://player.vimeo.com/video/783455051",
    freeVideoUrl: "https://player.vimeo.com/video/783455051?h=afd34abcd1",
    videoDuration: 5400,
    createdAt: "2025-04-10T15:00:00Z",
    updatedAt: "2025-04-10T15:00:00Z",
    published: true,
  },
  {
    id: "ui-basic-01",
    title: "レイアウトの考え方",
    description: "UIデザインの基本となるレイアウトの考え方について解説します",
    type: "video",
    categories: ["ui-design", "learning"],
    thumbnailUrl: "/placeholder.svg",
    accessLevel: "free",
    videoUrl: "https://player.vimeo.com/video/76979871",
    videoDuration: 1800,
    content: "<p>UIデザインの基本となるレイアウトの考え方について、実例を交えながら詳しく解説していきます。</p>",
    createdAt: "2025-04-01T10:00:00Z",
    updatedAt: "2025-04-01T10:00:00Z",
    published: true
  },
  {
    id: "ui-basic-02",
    title: "カラー設計の基本",
    description: "効果的なカラースキームの作り方とカラーシステムの構築方法",
    type: "video",
    categories: ["ui-design", "learning"],
    thumbnailUrl: "/placeholder.svg",
    accessLevel: "standard",
    videoUrl: "https://player.vimeo.com/video/783455051",
    freeVideoUrl: "https://player.vimeo.com/video/783455051?h=afd34abcd1",
    videoDuration: 2400,
    content: "<p>カラー設計の基本から応用まで、実践的な知識を解説します。</p>",
    freeContent: "<p>カラー設計の基本について、導入部分を解説します。より詳しい内容は会員限定です。</p>",
    createdAt: "2025-04-03T14:30:00Z",
    updatedAt: "2025-04-03T14:30:00Z",
    published: true
  }
];
